# please read more at https://employmenthero.atlassian.net/wiki/spaces/PLAT/pages/2570453361/Gitleaks#Local-scan-setup
# to set gitleaks scan on your local machine
repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.16.1
    hooks:
      - id: gitleaks-docker
