# This file is generate automatically by a platform tool
# You can modify the schedule but do not remove this file
# Please read more at https://employmenthero.atlassian.net/l/cp/uqVVmDT0
name: gitleaks-schedule-scan

on:
  schedule:
    - cron: '52 18 * * 5'
  workflow_dispatch:
jobs:
  gitleaks:
    uses: thinkei/eh-workflows/.github/workflows/gitleaks-schedule-scan.yml@main
    secrets: inherit
